export {
  DuplicateBlockSpecError,
  InvalidResolvedBlockSpecError,
  MissingBlockSpecError,
} from './errors.js';
export { BlockSpecRegistry, createBlockSpecRegistry } from './registry.js';
export type {
  BlockArgumentRef,
  BlockShape,
  BlockSpec,
  BlockSpecBindings,
  BlockSpecSource,
  BlockSpecResolver,
  BooleanBlockSpec,
  CommandBlockSpec,
  DefaultField,
  DefaultInput,
  FieldSpec,
  FieldSpecBindings,
  HatBlockSpec,
  HatStyle,
  InputAccepts,
  InputSpec,
  InputValueType,
  ReporterBlockSpec,
  ReporterOutputType,
  ScratchblocksBlockBinding,
  ScratchblocksFieldBinding,
  ScratchblocksFieldOption,
  ScratchBlocksSource,
  ScratchVmSource,
  StatementInputSpec,
  TerminalBlockSpec,
  ValueInputSpec,
} from './types.js';

export type {
  Block,
  BlockInput,
  Field,
  FieldType,
  Input,
  JsonObject,
  JsonPrimitive,
  JsonValue,
  Metadata,
  NumericKind,
  Opcode,
} from '@scratch-code/ast';
